plugins:
  keyword_glossary_enabled:
    default: true
    client: true
  keyword_glossary_entries:
    type: list
    default: ""
  keyword_glossary_trigger:
    default: "click"
    type: enum
    choices:
      - click
    client: true
  keyword_glossary_max_width:
    default: 320
    min: 220
    max: 600
    client: true
